"""Effective stress-energy in f(R) modified gravity on 4-D grids.

Extension beyond the MATLAB original. In the metric formalism the f(R)
field equations are (Sotiriou & Faraoni, arXiv:0805.1726, eq. 6, with
G = c = 1)

    F(R) R_munu - f(R)/2 g_munu
        + (g_munu Box - nabla_mu nabla_nu) F(R) = 8 pi T_munu

where F = df/dR. Given a metric, the matter stress-energy required to
source it therefore differs from the general-relativity answer by the
scalaron terms: curvature gradients act as an effective geometric
matter source. This lets the metric-first WarpFactory pipeline ask
whether a warp metric's exotic-matter requirement changes in a
modified-gravity theory (e.g. the Starobinsky R + alpha R^2 model)
rather than in pure general relativity.

For f(R) = R this reduces exactly to the Einstein field equations, so
FofRSolver(gr_model()) reproduces GridSolver to round-off.

Accuracy note: the Ricci scalar map is finite-differenced from the
metric, and the scalaron Hessian nabla nabla F is finite-differenced
from that map, so the scalaron terms carry one more level of stencil
error than the GR piece. Interior points of smooth metrics converge at
the stencil order; grid-boundary values inherit the one-sided-stencil
noise of the base solver.
"""

from dataclasses import dataclass, field
from typing import Callable

import numpy as np

from ..solver.tensor_utils import inverse_tensor
from .solver import GridSolver, christoffel_from_derivatives, ricci_from_derivatives
from .tensor import SpacetimeTensor, change_tensor_index, verify_tensor


@dataclass(frozen=True)
class FofRModel:
    """An f(R) Lagrangian and its derivative F = df/dR.

    Both callables map an ndarray of Ricci scalar values to an ndarray
    of the same shape. params records the model constants for
    provenance (copied into the output tensor's params).
    """

    f: Callable[[np.ndarray], np.ndarray]
    f_prime: Callable[[np.ndarray], np.ndarray]
    name: str = "f(R)"
    params: dict = field(default_factory=dict)


def gr_model() -> FofRModel:
    """f(R) = R: general relativity as the trivial member of the family."""
    return FofRModel(f=lambda R: R, f_prime=lambda R: np.ones_like(R), name="GR")


def starobinsky_model(alpha: float) -> FofRModel:
    """f(R) = R + alpha R^2 (Starobinsky 1980).

    The quadratic correction is the leading curvature term generated by
    quantum corrections to the Einstein-Hilbert action; alpha has units
    of length^2 in geometric units. alpha = 0 is general relativity.
    """
    return FofRModel(
        f=lambda R: R + alpha * R**2,
        f_prime=lambda R: 1.0 + 2.0 * alpha * R,
        name="Starobinsky",
        params={"alpha": alpha},
    )


class FofRSolver:
    """Effective matter stress-energy of a grid metric in f(R) gravity.

    Same metric-first contract as GridSolver: input a metric on a
    uniform 4-D grid, output the T_munu that the f(R) field equations
    demand. The curvature algebra (Christoffel, Ricci) is shared with
    GridSolver; only the scalaron terms are added on top.

    Parameters
    ----------
    model : FofRModel
        The f(R) Lagrangian; see gr_model / starobinsky_model
    order : int
        Finite difference accuracy order, 2 or 4
    """

    def __init__(self, model: FofRModel, order: int = 4):
        self.model = model
        self.grid_solver = GridSolver(order=order)
        self.order = order

    def ricci_scalar(self, metric: SpacetimeTensor) -> np.ndarray:
        """Ricci scalar map R = g^munu R_munu on the grid."""
        metric = change_tensor_index(metric, "covariant")
        g = np.asarray(metric.tensor, dtype=float)
        g_inv = inverse_tensor(g)
        ricci = self.grid_solver.ricci_tensor(g, g_inv, metric.scaling)
        return np.einsum("mn...,mn...->...", g_inv, ricci)

    def solve(
        self, metric: SpacetimeTensor, contravariant: bool = True
    ) -> SpacetimeTensor:
        """Effective stress-energy tensor of a grid metric in f(R) gravity.

        Parameters
        ----------
        metric : SpacetimeTensor
            Metric on a uniform 4-D grid
        contravariant : bool
            Return T^munu (GridSolver default) when True, T_munu
            otherwise

        Returns
        -------
        SpacetimeTensor
            Stress-energy tensor with type "stress-energy"; params
            record the f(R) model name and constants
        """
        if not verify_tensor(metric):
            raise ValueError(
                "Metric failed verification; see verify_tensor(metric, quiet=False)"
            )
        if metric.index.lower() != "covariant":
            metric = change_tensor_index(metric, "covariant")

        g = np.asarray(metric.tensor, dtype=float)
        g_inv = inverse_tensor(g)
        scaling = metric.scaling

        dg = self.grid_solver.metric_derivative1(g, scaling)
        d2g = self.grid_solver.metric_derivative2(g, scaling)
        ricci = ricci_from_derivatives(g, g_inv, dg, d2g)
        ricci_scalar = np.einsum("mn...,mn...->...", g_inv, ricci)

        F = np.asarray(self.model.f_prime(ricci_scalar), dtype=float)
        f_of_R = np.asarray(self.model.f(ricci_scalar), dtype=float)

        gamma = christoffel_from_derivatives(g_inv, dg)
        dF = self.grid_solver.scalar_derivative1(F, scaling)
        d2F = self.grid_solver.scalar_derivative2(F, scaling)
        # nabla_m nabla_n F = d_m d_n F - Gamma^a_mn d_a F
        hessian_F = d2F - np.einsum("amn...,a...->mn...", gamma, dF)
        box_F = np.einsum("mn...,mn...->...", g_inv, hessian_F)

        stress_energy = (F * ricci - 0.5 * f_of_R * g + g * box_F - hessian_F) / (
            8.0 * np.pi
        )
        index = "covariant"

        if contravariant:
            stress_energy = np.einsum(
                "ab...,ai...,bj...->ij...", stress_energy, g_inv, g_inv
            )
            index = "contravariant"

        params = {"order": self.order, "f_of_r_model": self.model.name}
        params.update(self.model.params)
        return SpacetimeTensor(
            tensor=stress_energy,
            type="stress-energy",
            index=index,
            coords=metric.coords,
            scaling=metric.scaling,
            name=metric.name,
            params=params,
        )
